### ISSUE TITLE
我直播的XML layout Design tag預覽頁面整個Activity 所有View元件都看不到

### ISSUE THREAD

**Issue by Squall-Huang** [luohaohaha/RTMPX#7]
我直播的XML layout Design tag預覽頁面整個Activity 所有View元件都會消失看不到
，但其他Activity跟Fragment都正常。
然後在Message會顯示下面的錯誤:
`java.lang.IllegalStateException: CameraX is not configured properly. The most likely cause is you did not include a default implementation in your build such as 'camera-camera2'.   at androidx.camera.core.CameraX.<init>(CameraX.java:109)   at androidx.camera.lifecycle.ProcessCameraProvider.getOrCreateCameraXInstance(ProcessCameraProvider.java:181)   at androidx.camera.lifecycle.ProcessCameraProvider.getInstance(ProcessCameraProvider.java:167)   at com.rtmpx.library.camera.widget.CameraXImplView.setUpCamera(CameraXImplView.java:159)   at com.rtmpx.library.camera.widget.CameraXImplView.onAttachedToWindow(CameraXImplView.java:154)   at android.view.View.dispatchAttachedToWindow(View.java:20753)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)   at android.view.AttachInfo_Accessor.setAttachInfo(AttachInfo_Accessor.java:58)`

但是我gradle有加:
```gradle
implementation "androidx.camera:camera-core:${camerax_version}"
implementation "androidx.camera:camera-camera2:${camerax_version}"
// If you want to additionally use the CameraX Lifecycle library
implementation "androidx.camera:camera-lifecycle:${camerax_version}"
// If you want to additionally use the CameraX View class
implementation "androidx.camera:camera-view:${camerax_version}"
```

不知道是什麼原因?

**Comment by Squall-Huang** [comment]
後來我導入cameraX  1.0.0有顯示xml後，再回到1.2.0-alpha02，就都有顯示xml預覽畫面了。
